version: '2'
services:
  default:
    links:
      - admin:admin
    ports:
      - 3000:3000
  admin:
    image: ${REPOSITORY_URI}:${COMMIT_HASH}
    environment:
      - NODE_ENV=local
      - AUTHORIZATION_KEYS=correct-key,other-key
