format_version: 4
common:
  deploy_job: &deploy_job
    resources:
      - docker
    tasks:
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_plan create
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_apply
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks wait_ecs

pipelines:
  'prm-deductions-administration-portal.dev':
    group: deductions
    label_template: '${git[:8]}'
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
      app:
        pipeline: prm-deductions-administration-portal
        stage: test_docker
      base_infra:
        pipeline: prm-deductions-infra
        stage: deploy_dev
    environment_variables:
      NHS_ENVIRONMENT: dev
    stages:
      - deploy:
          clean_workspace: true
          jobs:
            deploy: *deploy_job

      - test:
          clean_workspace: true
          jobs:
            smoke:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks smoke_test
  'prm-deductions-administration-portal.test':
    group: deductions
    label_template: '${git[:8]}'
    materials:
      git:
        type: configrepo
      dev_env:
        pipeline: prm-deductions-administration-portal.dev
        stage: test
      base_infra:
        pipeline: prm-deductions-infra
        stage: deploy_test
    environment_variables:
      NHS_ENVIRONMENT: test
    stages:
      - deploy:
          clean_workspace: true
          jobs:
            deploy: *deploy_job
      - test:
          clean_workspace: true
          jobs:
            smoke:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks smoke_test
